{{- if .Values.akvCertConfig.enabled }}
apiVersion: config.ratify.deislabs.io/v1beta1
kind: CertificateStore
metadata:
  name: certstore-akv
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  provider: azurekeyvault
  parameters:
    vaultURI: {{ required "vaultURI must be provided when AKV cert config is enabled" .Values.akvCertConfig.vaultURI  }}
    certificates:  |
      array:
        - |
          certificateName: {{ required "cert1Name must be provided when AKV cert config is enabled" .Values.akvCertConfig.cert1Name  }}
          certificateVersion: {{ .Values.akvCertConfig.cert1Version  }}       
        {{- if .Values.akvCertConfig.cert2Name }}
        - |
          certificateName: {{ .Values.akvCertConfig.cert2Name  }}
          certificateVersion: {{ .Values.akvCertConfig.cert2Version  }}        
        {{ end }}
    tenantID: {{ required "tenantID must be provided when AKV cert config is enabled" .Values.akvCertConfig.tenantId  }}    
    clientID: {{ required "clientID must be provided when use workload identity in akv" .Values.azureWorkloadIdentity.clientId  }}
{{ end }}